# Generated by Django 5.0.6 on 2026-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('data_upload', 'Data Upload'), ('data_validation', 'Data Validation'), ('data_processing', 'Data Processing'), ('model_training', 'Model Training'), ('model_activation', 'Model Activation'), ('prediction_generation', 'Prediction Generation'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_status_change', 'User Status Change'), ('user_role_change', 'User Role Change'), ('settings_change', 'Settings Change'), ('other', 'Other')], max_length=50),
        ),
    ]
