# Generated by Django 5.1.6 on 2026-09-19 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('officer', 'District Officer'), ('user', 'Youth'), ('viewer', 'Viewer'), ('researcher', 'Researcher')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('infrastructure_sector', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('roads', 'Roads'), ('internet', 'Internet'), ('sanitation', 'Sanitation'), ('other', 'Other')], help_text='Infrastructure sector where construction/work is planned', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Optional geographic sector/district for the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.location')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_reads',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['infrastructure_sector'], name='notificatio_infrast_5fbe58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_by'], name='notificatio_sent_by_90362a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user'], name='notificatio_user_id_29a5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['notification', 'user'], name='notificatio_notific_b051ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('notification', 'user')},
        ),
    ]
